create table if not exists public.draws (
  id bigint generated by default as identity primary key,
  external_draw_id text unique,
  draw_time timestamptz,
  numbers int[] not null default '{}',
  source text default 'stoloto',
  created_at timestamptz not null default now()
);

create table if not exists public.screenshot_sessions (
  id uuid primary key default gen_random_uuid(),
  target_draw_id text,
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.screenshots (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.screenshot_sessions(id) on delete cascade,
  target_draw_id text,
  storage_path text not null,
  captured_at timestamptz,
  received_at timestamptz not null default now(),
  recognized_numbers int[] not null default '{}',
  recognition_status text not null default 'pending',
  recognition_confidence numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.screenshot_draw_comparisons (
  id bigint generated by default as identity primary key,
  screenshot_id uuid references public.screenshots(id) on delete cascade,
  draw_id bigint references public.draws(id) on delete cascade,
  hits int[] not null default '{}',
  misses int[] not null default '{}',
  draw_numbers_absent_from_screenshot int[] not null default '{}',
  created_at timestamptz not null default now(),
  unique(screenshot_id, draw_id)
);

create table if not exists public.learning_observations (
  id bigint generated by default as identity primary key,
  draw_id bigint references public.draws(id) on delete cascade,
  observation_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.draws enable row level security;
alter table public.screenshot_sessions enable row level security;
alter table public.screenshots enable row level security;
alter table public.screenshot_draw_comparisons enable row level security;
alter table public.learning_observations enable row level security;

insert into storage.buckets (id, name, public)
values ('screenshots','screenshots',false)
on conflict (id) do nothing;
